### ISSUE TITLE
After 1 minute, time looses 2 hours

### ISSUE THREAD

**Issue by davidmetge** [rabits/flux-capacitor#1]
Hello,

I love your watchface! But there is a small issue.

I don't know where it comes from but the time displayed by the watchface is at first correct and then looses 2 hours (after 1 minute). Then it stays like that.

Example: it's 15:08 and I select your watchface. At 15:09, time on the watchface changes to 13:09.
If I open the menu (central button) and come back, the time is back to 15:09 again, until the next minute.

Thanks,

David

**Comment by rabits** [comment]
Hi, David

Thank you for the issue - I found and sorted it out: seems like I can't use tick_time from tick_handler.
Will be fixed soon in the next release 1.2

**Comment by rabits** [comment]
Done, v1.2 release is out.
